site_name: Tilemap Creator 3D Docs
theme:
    logo: img/logo.png
    name: readthedocs

extra_css: [style/overwrites.css]

markdown_extensions:
    admonition: {}

nav:
    - Home: "index.md"
    - Manual:
        - Getting started: "getting-started.md"
        - Tiles: "tiles.md"
        - Modules: "modules.md"
        - Samples: "samples.md"
        - Writing Extensions: "extensions.md"
        - FAQ: "faq.md"
    - Scripting API:
        - 'Tilemap3D': "api/Tilemap3D.md"
        - 'TilemapData': "api/TilemapData.md"
        - 'TilePalette': "api/TilePalette.md"
        - 'BaseTile': "api/BaseTile.md"
        - 'SingleTile': "api/SingleTile.md"
        - 'MultiTile': "api/MultiTile.md"
        - 'AutoTile': "api/AutoTile.md" 
        - 'ITilemapModule': "api/ITilemapModule.md"
        - 'TilemapMesh': "api/TilemapMesh.md"
        - 'TilemapCollider': "api/TilemapCollider.md"
        - 'TilemapNavigator': "api/TilemapNavigator.md"
        - 'TilemapSettings': "api/TilemapSettings.md"
        - 'TilemapGUIUtility': "api/TilemapGUIUtility.md"